tests: add support for LoongArch
The test results of running "make check" with qemu 7.2 are as follows:
============================================================================
Testsuite summary for GRUB 2.11
============================================================================
============================================================================

These ERROR cases need to be run as root user:
  ERROR: ext234_test
  ERROR: hfsplus_test
  ERROR: ntfs_test
  ERROR: reiserfs_test
  ERROR: fat_test
  ERROR: minixfs_test
  ERROR: xfs_test
  ERROR: f2fs_test
  ERROR: nilfs2_test
  ERROR: romfs_test
  ERROR: exfat_test
  ERROR: udf_test
  ERROR: hfs_test
  ERROR: jfs_test
  ERROR: btrfs_test
  ERROR: zfs_test
  ERROR: luks1_test
  ERROR: luks2_test
  ERROR: grub_cmd_cryptomount

These test cases are skipped:
  SKIP: pata_test
  SKIP: ahci_test
  SKIP: uhci_test
  SKIP: ohci_test
  SKIP: ehci_test
  SKIP: fddboot_test
  SKIP: netboot_test
  SKIP: pseries_test

This test case fails because of: qemu-system-loongarch64: ram_size must be greater than 1G.
  FAIL: grub_func_test

Signed-off-by: Xiaotian Wu <wuxiaotian@loongson.cn>